### PR TITLE
Create validity and genvalidity packages for 'dlist'

### PR DESCRIPTION
**Pull request by clintonmead**
In preparation for adding instances to `autodocodec` for `DList` and `DNonEmpty`

### CODE REVIEW

**Comment by NorfairKing** [comment]
Nice! I'll start using these for my `Validation`s!
Building now, will merge in a moment.

**Comment by NorfairKing** [comment]
I'm ready to merge and release @clintonmead , are you ready?

**Comment by clintonmead** [comment]
@NorfairKing hold up sorry I shouldn't have opened this PR so soon. Something is causing `Data.DList.DNonEmpty.fromList: empty list` in the autodocodec tests so I've mucked up the generator for `DNonEmpty`.

**Comment by clintonmead** [comment]
@NorfairKing okay we're good now :)

**Comment by clintonmead** [comment]
@NorfairKing see https://github.com/NorfairKing/autodocodec/pull/55 for the autodocodec PR

**Comment by NorfairKing** [comment]
Merged manually and released.

**Comment by clintonmead** [comment]
@NorfairKing the commit you need to merge is https://github.com/NorfairKing/validity/commit/ae3cc278864f27631eab3aabbbacd26890ce09c2 but I think you've merged https://github.com/NorfairKing/validity/commit/c0c44a6f29e4b13811da2240682e09e53e342e47. 

https://github.com/NorfairKing/validity/blob/master/genvalidity-dlist/src/Data/GenValidity/DNonEmpty.hs in master is different to in this PR: https://github.com/clintonmead/validity/blob/ae3cc278864f27631eab3aabbbacd26890ce09c2/genvalidity-dlist/src/Data/GenValidity/DNonEmpty.hs

**Comment by NorfairKing** [comment]
@clintonmead oh shoot :(

**Comment by NorfairKing** [comment]
@clintonmead I think I did it right this time.

**Pull request closed without merging**
