### PR TITLE
s/optics/lens/

### LINKED ISSUE #70: genvalidity-hspec-optics is named confusingly
It's about `lens` not `optics`!

### PR DESCRIPTION
**Pull request by phadej**
Resolve #70

### CODE REVIEW

**Comment by NorfairKing** [comment]
I can merge this as-is, if you prefer, but do we want to also change the package name?

**Comment by phadej** [comment]
I don't think changing name is worth it alone.

If you'd actually make both `genvalidity-hspec-optics` *and* `genvalidity-hspec-lens`, then it would make sense. But as far as there isn't package with specs for `optics`, the name is ok.

**Comment by NorfairKing** [comment]
Ok cool. I'll merge then. If your confusion was motivated by `genvalidity-optics` (the right one) not existing, then maybe you're going to write that?

**Comment by phadej** [comment]
@NorfairKing I won't. I just was looking for `optics` packages on Stackage, and this one caught my attention. I wondered how `*-optics` can be there when `optics` is not.

Hopefully the new synopsis (and description) would resolve such confusions sooner.

**Comment by NorfairKing** [comment]
Aha, got it! Unrelated: I saw you at the Helsinki haskell meetup about validity but you left too soon for me to say hi.

**Comment by phadej** [comment]
Oh yes, I was there, but unfortunately had to be elsewhere later that evening

**Pull request merged**
